CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONFIDENTIAL
C	Property of United States Steel Corporation
C	Copyright 2007 United States Steel Corporation
C	All rights reserved.
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	PROGRAM	BTUMX
C
C	PROGRAM GETS TURNED ON BY BOB MAKI CALCULATES THE BEFORE
C	TUMBLE NUMBER FOR EACH PLANT
C
C
C	REVISION IM800136 WJB 04-05-2011 ADDED CPMPRESSION %<300
C
	IMPLICIT NONE
C
	STRUCTURE	/MAKI/
		CHARACTER*4	KEYX
		REAL*4		MSIL(3,31)
		REAL*4		CR12(3,31)
		REAL*4		FLFR(3,31)
		REAL*4		FLFS(3,31)
		REAL*4		FLS(3,31)
		REAL*4		FLTS(3,31)
		REAL*4		AEFF(4,3,31)
	END STRUCTURE
C
	RECORD/MAKI/REC
C
	INTEGER*4	I,J,K,L,M,N,UFO_OPEN
	INTEGER*4	FLAG/64/,STAT,SYS$CREPRC
C
	CHARACTER*12	DATX,DATEX,SDATE
	CHARACTER*4	KEYD
	CHARACTER*23	DATETIME
C
	REAL*8		STEP2(8),STEP3(8),ACCUM,OBS,L300(2)
	REAL*8		BT2(9),BT3(9),BT2X(3),BT3X(5),FLF(2)
	REAL*8		TX(2),PH2(9),PH3(9),STEPX(9)
	REAL*8		TN2X(3),TN3X(5)
C
	REAL*4		VALU(24),AGL(6)
C
	EXTERNAL	UFO_OPEN
C
	OPEN	(UNIT=1,FILE='OREM:TURNON.DAT',STATUS='UNKNOWN',
	1	ACCESS='APPEND')
C
	CALL	LIB$DATE_TIME(DATETIME)
C
	WRITE	(1,4000)DATETIME
4000	FORMAT	(' BTUMX PROGRAM TURNON  ',A)
C
	CLOSE	(UNIT=1)
C
	OPEN	(UNIT=2,FILE='MET_P:WJBBTX.DAT',STATUS='OLD',
	1	SHARED,USEROPEN=UFO_OPEN)
C
	READ	(2,11)DATEX,BT2,BT3,FLF,TX,L300	!GET NUMBERS FROM MAKI
11	FORMAT	(A,20F7.2,2F7.1,2F7.2)
C
	CLOSE	(UNIT=2)
C
	DO 20	I=1,7
C
		PH2(I)=BT2(I)	!PUT SEVEN PHYSICALS FOR
		PH3(I)=BT3(I)	!EACH STEP INTO A TABLE
		STEPX(I)=STEP2(I)
C
20	CONTINUE
C
	PH2(9)=TX(1)	!ADD TONS TO
	PH3(9)=TX(2)	!EACH TABLE
	STEPX(9)=STEP2(9)	!DO THIS TO FAKE OUT TONS
	STEPX(8)=STEP2(8)
	PH2(8)=L300(1)
	PH3(8)=L300(2)	!ADD %<300 TO EACH TABLE
C
	OPEN	(UNIT=1,FILE='OREM:BTUM.DAT',STATUS='OLD',
	1	 ACCESS='DIRECT',RECORDTYPE='FIXED',
	1	 FORM='UNFORMATTED',RECL=35,SHARED,USEROPEN=UFO_OPEN)
C
	DO 110	N=9,1,-1	!WE WILL PROCESS TONS FIRST
C
	DO 100	I=1,100
		READ	(1,REC=I)DATX,STEP2,STEP3
		IF (DATX(1:1) .EQ. ' ')DATX(1:1)='0'
		IF (DATX .EQ. DATEX)THEN	!FIND SHIFT FOR THESE NUMBERS
C
			OPEN	(UNIT=2,FILE='OREM:BTUMX.DAT',STATUS='OLD',
	1	 		ACCESS='DIRECT',RECORDTYPE='FIXED',
	1	 		FORM='UNFORMATTED',RECL=16)
C
			READ	(2,REC=N)BT2X,BT3X
C
			IF (STEPX(N) .EQ. 0)THEN	!FIRST RUN ROLL NUMBERS
				IF (PH2(N) .EQ. 0)GOTO 198 !DONT ROLL IN A ZERO
				BT2X(3)=BT2X(2)
				BT2X(2)=BT2X(1)
				BT2X(1)=PH2(N)
198				CONTINUE
				IF (PH3(N) .EQ. 0)GOTO 200 !DONT ROLL IN A ZERO
				BT3X(5)=BT3X(4)
				BT3X(4)=BT3X(3)
				BT3X(3)=BT3X(2)
				BT3X(2)=BT3X(1)
				BT3X(1)=PH3(N)
			ELSE
				IF (PH2(N) .EQ. 0)GOTO 199 !DONT ROLL IN A ZERO
				BT2X(1)=PH2(N)	!OTHERWISE MAKE CHANGE
199				CONTINUE
				IF (PH3(N) .EQ. 0)GOTO 200 !DONT ROLL IN A ZERO
				BT3X(1)=PH3(N)
			END IF
C						
200			CONTINUE
C
			IF (N .EQ. 9)THEN
C
				TN2X(1)=BT2X(1)	!SAVE STEP 2 TONS
				TN2X(2)=BT2X(2)
				TN2X(3)=BT2X(3)
C
				TN3X(1)=BT3X(1)	!SAVE STEP 3 TONS
				TN3X(2)=BT3X(2)
				TN3X(3)=BT3X(3)
				TN3X(4)=BT3X(4)
				TN3X(5)=BT3X(5)
C
				GOTO 500	!SKIP THE WT AVG SECTION
C
			END IF
C
			ACCUM=0
			OBS=0
C
			DO 300 K=1,3
				IF ((BT2X(K) .NE. 0)
	1				.OR.(TN2X(K) .NE. 0))THEN
					ACCUM=ACCUM+(BT2X(K)*TN2X(K))
					OBS=OBS+TN2X(K)
				END IF
C		
300			CONTINUE
C
			STEP2(N)=0
			IF (OBS .NE. 0)STEP2(N)=ACCUM/OBS
C
			ACCUM=0
			OBS=0
C
			DO 400 K=1,5
				IF ((BT3X(K) .NE. 0)
	1				.OR.(TN3X(K) .NE. 0))THEN
					ACCUM=ACCUM+(BT3X(K)*TN3X(K))
					OBS=OBS+TN3X(K)
				END IF
C		
400			CONTINUE
C
			STEP3(N)=0
			IF (OBS .NE. 0)STEP3(N)=ACCUM/OBS
C
500			CONTINUE
C
			WRITE	(2,REC=N)BT2X,BT3X	!SEND CHANGES	
C
			CLOSE	(UNIT=2)
C
			WRITE	(1,REC=I)DATX,STEP2,STEP3
C
	OPEN	(UNIT=3,FILE='OREM:BTUMO.DAT',STATUS='OLD',
	1	 ACCESS='DIRECT',RECORDTYPE='FIXED',
	1	 FORM='UNFORMATTED',RECL=35,SHARED,USEROPEN=UFO_OPEN)
C
			WRITE	(3,REC=1)DATX,STEP2,STEP3
C
			CLOSE	(UNIT=3)
C
C	CALL	LIB$SPAWN('SUBMIT/NOL/USER=ORACLE OREM:BTUMO.COM',,,FLAG)
C
			STAT=	SYS$CREPRC(,'SYS$SYSTEM:LOGINOUT.EXE',
	1			'OREM:BTUMX.COM','NL:','NL:',,,,,,,)
C
			IF (.NOT. STAT)THEN	!TURN ON ERROR
				OPEN (UNIT=2,FILE='OREM:BTUMX.ERR',
	1				STATUS='UNKNOWN')
				WRITE	(UNIT=2,FMT=333)DATETIME,STAT
333				FORMAT	(' SYS$CREPRC ERROR   ',A,2X,I5)
				CLOSE	(UNIT=2)
			END IF
C
			GOTO 110
C
		END IF
C
100	CONTINUE
C
110	CONTINUE
C
	OPEN	(UNIT=2,FILE='LOGS:STREND.DAT',
	1	 STATUS='OLD',
	1	 ACCESS='DIRECT',RECORDTYPE='FIXED',
	1	 FORM='UNFORMATTED',RECL=27,SHARED,USEROPEN=UFO_OPEN)
C
	READ	(2,REC=1)SDATE,VALU
C
	IF (SDATE(1:1) .EQ. ' ')SDATE(1:1)='0'
C
	IF (DATEX(12:12) .NE. SDATE(12:12))GOTO 99999	!CHECK SHIFT
	IF (DATEX(1:2) .NE. SDATE(1:2))GOTO 99999	!CHECK DAY
C
	VALU(8)=BT2(8)	!STEP 2 LINE PELLETS
	VALU(9)=BT2(9)	!STEP 2 FIL CAKE
	VALU(10)=BT3(8)	!STEP 3 LINE PELLETS
	VALU(11)=BT3(9)	!STEP 3 FIL CAKE
	VALU(12)=FLF(1)	!FLOT SIO2
	VALU(13)=FLF(2)	!FLOT -270
C
	CALL	OTS$CVT_TI_L(SDATE(12:12),I,,%VAL(1)) !SHIFT
	CALL	OTS$CVT_TI_L(SDATE(1:2),J,,%VAL(1))   !DAY
	KEYD(1:2)=SDATE(10:11)
	IF (SDATE(4:6) .EQ. 'JAN')KEYD(3:4)='01'
	IF (SDATE(4:6) .EQ. 'FEB')KEYD(3:4)='02'
	IF (SDATE(4:6) .EQ. 'MAR')KEYD(3:4)='03'
	IF (SDATE(4:6) .EQ. 'APR')KEYD(3:4)='04'
	IF (SDATE(4:6) .EQ. 'MAY')KEYD(3:4)='05'
	IF (SDATE(4:6) .EQ. 'JUN')KEYD(3:4)='06'
	IF (SDATE(4:6) .EQ. 'JUL')KEYD(3:4)='07'
	IF (SDATE(4:6) .EQ. 'AUG')KEYD(3:4)='08'
	IF (SDATE(4:6) .EQ. 'SEP')KEYD(3:4)='09'
	IF (SDATE(4:6) .EQ. 'OCT')KEYD(3:4)='10'
	IF (SDATE(4:6) .EQ. 'NOV')KEYD(3:4)='11'
	IF (SDATE(4:6) .EQ. 'DEC')KEYD(3:4)='12'
C
	OPEN	(UNIT=90,FILE='MET_P:HALFSIL2.DAT',ACCESS='KEYED',
	1	SHARED,READONLY,ERR=120,STATUS='OLD')
C
	READ	(90,ERR=120,KEYEQ=KEYD,KEYID=0)REC
C
	VALU(19)=REC.FLTS(I,J)	!FLOT TAILS SIO2
C
120	CONTINUE
C
	WRITE	(2,REC=1)SDATE,VALU
C
99999	CONTINUE
C
	CLOSE	(UNIT=1)
	CLOSE	(UNIT=2)
	CLOSE	(UNIT=90)
C
	CALL	LIB$WAIT(10.0)
C
	CALL	EXIT
C
	END
C
